# Generated by Django 4.2 on 2024-11-15 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 15, 21, 58, 37622, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
