# Generated by Django 4.2 on 2024-11-15 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_product_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, max_length=555, verbose_name='Описание продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 15, 24, 26, 835344, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
