# Generated by Django 4.2 on 2024-11-16 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_category_publish_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 13, 3, 2, 996735, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 13, 3, 2, 997239, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
