# Generated by Django 4.2 on 2024-11-15 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_product_body_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Нажмите на если хотите опубликовать.', verbose_name='Публикация продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 15, 25, 52, 249211, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
