# Generated by Django 4.2 on 2024-11-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='media/category', verbose_name='Изображение рецепта'),
            preserve_default=False,
        ),
    ]
