# Generated by Django 4.2 on 2024-11-15 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_product_is_published_alter_product_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Нажмите на если хотите опубликовать категорию.', verbose_name='Публикация продукта'),
        ),
        migrations.AddField(
            model_name='category',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 15, 28, 37, 498925, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Нажмите на если хотите опубликовать продукт.', verbose_name='Публикация продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 15, 28, 37, 499486, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
