# Generated by Django 4.2 on 2024-11-16 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите логин поьзователя', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Не корректное поле.', regex='^[\\w.@+-]+\\Z')], verbose_name='Логин'),
        ),
    ]
