[
    {
        "model": "review.Category",
        "pk": 1,
        "fields": {
            "title": "Science",
            "slug": "science",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.325895+00:00",
            "parent": null,
            "lft": 1,
            "rght": 6,
            "tree_id": 1,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 2,
        "fields": {
            "title": "Get",
            "slug": "get",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.325947+00:00",
            "parent": null,
            "lft": 1,
            "rght": 2,
            "tree_id": 2,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 3,
        "fields": {
            "title": "Beyond",
            "slug": "beyond",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.325969+00:00",
            "parent": null,
            "lft": 1,
            "rght": 2,
            "tree_id": 3,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 4,
        "fields": {
            "title": "Sort",
            "slug": "sort",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.325986+00:00",
            "parent": null,
            "lft": 1,
            "rght": 2,
            "tree_id": 4,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 5,
        "fields": {
            "title": "Board",
            "slug": "board",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.326001+00:00",
            "parent": null,
            "lft": 1,
            "rght": 2,
            "tree_id": 5,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 6,
        "fields": {
            "title": "Manage",
            "slug": "manage",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.326014+00:00",
            "parent": null,
            "lft": 1,
            "rght": 2,
            "tree_id": 6,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 7,
        "fields": {
            "title": "Wear",
            "slug": "wear",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.326026+00:00",
            "parent": null,
            "lft": 1,
            "rght": 2,
            "tree_id": 7,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 8,
        "fields": {
            "title": "Western",
            "slug": "western",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.326038+00:00",
            "parent": null,
            "lft": 1,
            "rght": 2,
            "tree_id": 8,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 9,
        "fields": {
            "title": "We",
            "slug": "we",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.326057+00:00",
            "parent": null,
            "lft": 1,
            "rght": 2,
            "tree_id": 9,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 10,
        "fields": {
            "title": "Someone",
            "slug": "someone",
            "is_published": true,
            "publish": "2024-11-16T16:21:29.326070+00:00",
            "parent": null,
            "lft": 1,
            "rght": 2,
            "tree_id": 10,
            "level": 0,
        },
    },
    {
        "model": "review.Category",
        "pk": 11,
        "fields": {
            "title": "Physics",
            "slug": "physics",
            "is_published": true,
            "publish": "2024-11-16T17:21:29.325895+00:00",
            "parent": 1,
            "lft": 2,
            "rght": 3,
            "tree_id": 1,
            "level": 1,
        },
    },
    {
        "model": "review.Category",
        "pk": 12,
        "fields": {
            "title": "Chemistry",
            "slug": "chemistry",
            "is_published": true,
            "publish": "2024-11-16T17:21:29.325895+00:00",
            "parent": 1,
            "lft": 4,
            "rght": 5,
            "tree_id": 1,
            "level": 1,
        },
    },
    {
        "model": "review.Category",
        "pk": 13,
        "fields": {
            "title": "API",
            "slug": "api",
            "is_published": true,
            "publish": "2024-11-16T18:21:29.325947+00:00",
            "parent": 2,
            "lft": 2,
            "rght": 5,
            "tree_id": 2,
            "level": 1,
        },
    },
    {
        "model": "review.Category",
        "pk": 14,
        "fields": {
            "title": "REST",
            "slug": "rest",
            "is_published": true,
            "publish": "2024-11-16T18:21:29.325947+00:00",
            "parent": 13,
            "lft": 3,
            "rght": 4,
            "tree_id": 2,
            "level": 2,
        },
    },
]
